### ISSUE TITLE
Cannot `npm install` the application

### ISSUE THREAD

**Issue by maephisto** [futurice/pepperoni-app-kit#24] opened 2016-05-25 08:29 UTC
I am getting an "Permission denied" error:

`npm install
Password:
The authenticity of host 'github.com (192.30.252.129)' can't be established.
RSA key fingerprint is SHA256:xxxxxx.
//e you sure you want to continue connecting (yes/no)? -
npm ERR! git fetch -a origin (ssh://git@github.com/futurice/react-native-lock.git) Warning: Permanently added 'github.com,192.30.252.129' (RSA) to the list of known hosts.
npm ERR! git fetch -a origin (ssh://git@github.com/futurice/react-native-lock.git) Permission denied (publickey).
npm ERR! git fetch -a origin (ssh://git@github.com/futurice/react-native-lock.git) fatal: Could not read from remote repository.
npm ERR! git fetch -a origin (ssh://git@github.com/futurice/react-native-lock.git)
npm ERR! git fetch -a origin (ssh://git@github.com/futurice/react-native-lock.git) Please make sure you have the correct access rights
npm ERR! git fetch -a origin (ssh://git@github.com/futurice/react-native-lock.git) and the repository exists.
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code 128

npm ERR! Command failed: git fetch -a origin
npm ERR! Warning: Permanently added 'github.com,192.30.252.129' (RSA) to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>`

**Comment by jevakallio** [comment] 2016-05-25 08:36
@maephisto this sounds like same problem as https://github.com/futurice/pepperoni-app-kit/issues/21 . When did you clone the repository? Could you try using the latest package.json from master (updated yesterday)?

If that doesn't work, let us know and we'll take a look. In the meantime the way to fix this is to configure your ssh client as per the GitHub SSH instructions.

**Comment by maephisto** [comment] 2016-05-25 09:21
Thanks @jevakallio ! I pulled the master and tried again. I can confirm that now it's working.

**Comment by jevakallio** [comment] 2016-05-25 09:25
Closing as duplicate of #21

**Closed by jevakallio** 2016-05-25 09:25 UTC
