### ISSUE TITLE
Build issues with Lock

### ISSUE THREAD

**Issue by GeoffreyPlitt** [futurice/pepperoni-app-kit#86] opened 2016-07-19 18:32 UTC
Any ideas?

:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources
/Users/giro/stardust-app/android/app/src/main/res/values/styles.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'Lock.Theme'.
/Users/giro/stardust-app/android/app/src/main/res/values/styles.xml:12:17-33 : No resource found that matches the given name: attr 'Auth0.Background'.
/Users/giro/stardust-app/android/app/src/main/res/values/styles.xml:15:17-36 : No resource found that matches the given name: attr 'Auth0.CredentialBox'.
/Users/giro/stardust-app/android/app/src/main/res/values/styles.xml:16:17-38 : No resource found that matches the given name: attr 'Auth0.CredentialField'.
/Users/giro/stardust-app/android/app/src/main/res/values/styles.xml:17:17-44 : No resource found that matches the given name: attr 'Auth0.CredentialField.Email'.
/Users/giro/stardust-app/android/app/src/main/res/values/styles.xml:18:17-47 : No resource found that matches the given name: attr 'Auth0.CredentialField.Password'.
/Users/giro/stardust-app/android/app/src/main/res/values/styles.xml:19:17-47 : No resource found that matches the given name: attr 'Auth0.CredentialField.Username'.
/Users/giro/stardust-app/android/app/src/main/res/values/styles.xml:20:17-30 : No resource found that matches the given name: attr 'Auth0.Message'.
/Users/giro/stardust-app/android/app/src/main/res/values/styles.xml:13:17-41 : No resource found that matches the given name: attr 'Auth0.PrimaryButtonStyle'.
/Users/giro/stardust-app/android/app/src/main/res/values/styles.xml:14:17-43 : No resource found that matches the given name: attr 'Auth0.SecondaryButtonStyle'.
/Users/giro/stardust-app/android/app/src/main/res/values/styles.xml:21:17-38 : No resource found that matches the given name: attr 'Auth0.Separator.Color'.
/Users/giro/stardust-app/android/app/src/main/res/values/styles.xml:10:17-33 : No resource found that matches the given name: attr 'Auth0.Title.Icon'.
/Users/giro/stardust-app/android/app/src/main/res/values/styles.xml:11:17-33 : No resource found that matches the given name: attr 'Auth0.Title.Text'.
/Users/giro/stardust-app/android/app/src/main/res/values/styles.xml:71:17-44 : No resource found that matches the given name: attr 'com_auth0_errorIconDrawable'.
/Users/giro/stardust-app/android/app/src/main/res/values/styles.xml:70:17-45 : No resource found that matches the given name: attr 'com_auth0_normalIconDrawable'.
/Users/giro/stardust-app/android/app/src/main/res/values/styles.xml:71:17-44 : No resource found that matches the given name: attr 'com_auth0_errorIconDrawable'.
/Users/giro/stardust-app/android/app/src/main/res/values/styles.xml:70:17-45 : No resource found that matches the given name: attr 'com_auth0_normalIconDrawable'.
/Users/giro/stardust-app/android/app/src/main/res/values/styles.xml:71:17-44 : No resource found that matches the given name: attr 'com_auth0_errorIconDrawable'.
/Users/giro/stardust-app/android/app/src/main/res/values/styles.xml:70:17-45 : No resource found that matches the given name: attr 'com_auth0_normalIconDrawable'.
/Users/giro/stardust-app/android/app/src/main/res/values/styles.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'Lock.Theme.Title.Icon'.
/Users/giro/stardust-app/android/app/src/main/res/values/styles.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'Lock.Theme.Title.Text'.

:app:processDebugResources FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:processDebugResources'.
  
  > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/local/opt/android-sdk/build-tools/23.0.1/aapt'' finished with non-zero exit value 1
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.109 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
vlt062:stardust-app giro$

**Comment by stefanwuest** [comment] 2016-07-22 14:41
I'm having the same issue. Haven't found a solution yet. If somebody jumps in here. I want to scrap Auth0 altogether. Anything I have to consider?

**Comment by fabriziomoscon** [comment] 2016-07-22 18:09
@GeoffreyPlitt 
I have just made a fresh install on Linux and macosx

```
git clone ...
npm install
react-native run-android
```

and everything seems fine.
Which version of node and npm are you on, which system. What is the output of `react-native -v`?

you can also try to use `gradlew` directly to build and see if that makes any difference.

```
cd android
./gradlew assembleDebug
./gradlew installDebug
```

@stefanwuest I am not using Auth0 in my projects based on Pepperoni. Which auth module would you like to see and why

**Comment by stefanwuest** [comment] 2016-07-25 06:03
These are the versions I'm currently using:
```
$ react-native -v
react-native-cli: 1.0.0
react-native: 0.29.2
$ npm -v
3.10.2
$ node -v
v6.2.2
```

Building with gradlew threw the same error...

@fabriziomoscon Undecided — currently still looking at other options.

**Comment by fabriziomoscon** [comment] 2016-07-26 09:11
If that helps I am actually running an older `react-native`

```
react-native -v                       
react-native-cli: 0.2.0
```

I am using facebook-account-kit for auth, so I scraped most of auth0 out of the the project.

**Comment by stefanwuest** [comment] 2016-07-28 08:06
I resolved the problem for me by removing Auth0 stuff from the following files:

android/app/app.iml
```
<orderEntry type="module" module-name="react-native-lock" exported="" />
```

android/app/src/main/AndroidManifest.xml
```
      <!--Auth0 Lock-->
      <activity
        android:name="com.auth0.lock.LockActivity"
        android:theme="@style/AppTheme.Lock.Theme"
        android:screenOrientation="portrait"
        android:launchMode="singleTask">
      </activity>
      <!--Auth0 Lock End-->
      <!--Auth0 Lock Embedded WebView-->
      <activity
          android:name="com.auth0.identity.web.WebViewActivity"
          android:theme="@style/AppTheme.Lock.Theme">
      </activity>
      <!--Auth0 Lock Embedded WebView End-->
      <!--Auth0 Lock Passwordless-->
      <activity
          android:name="com.auth0.lock.passwordless.LockPasswordlessActivity"
          android:theme="@style/AppTheme.Lock.Theme"
          android:screenOrientation="portrait"
          android:launchMode="singleTask">
      </activity>
      <activity
          android:name="com.auth0.lock.passwordless.CountryCodeActivity"
          android:theme="@style/AppTheme.Lock.Theme">
      </activity>
      <!--Auth0 Lock Passwordless End-->
```

android/app/src/main/res/values/styles.xml
```
<style name="AppTheme.Lock.Theme.CredentialField" parent="Widget.AppCompat.EditText">
    <item name="android:layout_width">match_parent</item>
    <item name="android:layout_height">@dimen/com_auth0_credential_field_height</item>
    <item name="android:textSize">@dimen/com_auth0_credential_field_font_size</item>
    <item name="android:textColorHint">#ffffff</item>
    <item name="android:paddingLeft">@dimen/com_auth0_credential_field_padding</item>
    <item name="android:paddingRight">@dimen/com_auth0_credential_field_padding</item>
    <item name="android:paddingBottom">@dimen/com_auth0_credential_field_vertical_padding</item>
    <item name="android:paddingTop">@dimen/com_auth0_credential_field_vertical_padding</item>
    <item name="android:drawablePadding">@dimen/com_auth0_credential_field_icon_right_padding</item>
    <item name="android:background">@color/com_auth0_credential_field_background</item>
    <item name="android:textCursorDrawable">@drawable/com_auth0_cursor</item>
  </style>

  <style name="AppTheme.Lock.Theme.CredentialField.Email" parent="AppTheme.Lock.Theme.CredentialField">
    <item name="android:textColor">#ffffff</item>
    <item name="com_auth0_normalIconDrawable">@drawable/com_auth0_ic_email</item>
    <item name="com_auth0_errorIconDrawable">@drawable/com_auth0_ic_email_error</item>
  </style>

  <style name="AppTheme.Lock.Theme.CredentialField.Password" parent="AppTheme.Lock.Theme.CredentialField">
    <item name="android:textColor">#ffffff</item>
    <item name="com_auth0_normalIconDrawable">@drawable/com_auth0_ic_lock</item>
    <item name="com_auth0_errorIconDrawable">@drawable/com_auth0_ic_lock_error</item>
  </style>

  <style name="AppTheme.Lock.Theme.CredentialField.Username" parent="AppTheme.Lock.Theme.CredentialField">
    <item name="android:textColor">#ffffff</item>
    <item name="com_auth0_normalIconDrawable">@drawable/com_auth0_ic_person</item>
    <item name="com_auth0_errorIconDrawable">@drawable/com_auth0_ic_person_error</item>
  </style>

  <style name="AppTheme.Lock.Theme.Message" parent="TextAppearance.AppCompat.Small">
     <item name="android:layout_marginBottom">@dimen/com_auth0_lock_vertical_margin</item>
     <item name="android:textColor">#ffffff</item>
  </style>
```

**Comment by cciszak** [comment] 2016-07-30 13:55
got exactly same problem :(

**Comment by jevakallio** [comment] 2016-08-07 11:40
@GeoffreyPlitt @chrisciszak thanks for reporting the issue. I am unable to reproduce it on OSX. These are the steps I tried, could you tell me what you are doing differently?
```
# clone fresh copy
git clone git@github.com:futurice/pepperoni-app-kit.git pepperoni-fresh && cd pepperoni-fresh

# install deps and configure
npm i
cp env.example.js env.js

# run (assumes running android emulator)
react-native run-android
```

**Comment by 0redd** [comment] 2016-08-20 00:39
I've got the same problem :(, thank's @stefanwuest for the workaround

**Comment by tino-junge** [comment] 2016-11-25 17:53
Closing this issue now since we've now made Auth0 optional for pepperoni :)

**Comment by zzswang** [comment] 2016-11-27 10:58
still have same issue...

**Comment by tino-junge** [comment] 2016-11-28 10:05
Hi @zzswang, have you tried cloning a fresh version of Pepperoni recently? It doesn't have the Auth0 dependency anymore. Or do you want to use Auth0?

**Comment by zzswang** [comment] 2016-11-29 02:40
I don't want to use Auth0 for the beginning. Maybe later.

I followed the steps listed above by jevakallio, then got the same issue.

```
# clone fresh copy
git clone git@github.com:futurice/pepperoni-app-kit.git pepperoni-fresh && cd pepperoni-fresh

# install deps and configure
npm i
cp env.example.js env.js

# run (assumes running android emulator)
react-native run-android
```

**Comment by tino-junge** [comment] 2016-12-02 17:02
Hi @zzswang can you try to use another name for your repo (without a `-`) and rerun the same setup? You could also just clone a fresh copy of pepperoni and try to build it without the renaming script. If this doesn't help please post the error message you're getting here.

**Comment by zzswang** [comment] 2016-12-06 13:13
@tino-junge  remove "-" from the folder name. Everything is ok.

Thanks a lot. :)

**Comment by tino-junge** [comment] 2016-12-07 15:11
Great, to hear :) will close this issue now

**Closed by tino-junge** 2016-12-07 15:11 UTC
