### ISSUE TITLE
npm install fails, don't have public key for react-native-lock

### ISSUE THREAD

**Issue by VashMar** [futurice/pepperoni-app-kit#21] opened 2016-05-24 20:31 UTC
The "react-native-lock" package requires ssh access in order to compile, is this the expected behavior? If so what should the workaround be? We've tried removing it from the package.json and installing running npm install on the "react-native-lock" lib separately, but we believe that's leading us to an A0RNLock issue.

**Comment by krivachy** [comment] 2016-05-24 20:51
No, that is not the intended behavior. 
@VashMar, can you quickly try: `git://github.com/futurice/react-native-lock.git#feature/customizedTheme` as the package location?

**Comment by kimmobrunfeldt** [comment] 2016-05-24 20:52
I changed the ssh git url to GitHub url which npm supports. https://github.com/futurice/pepperoni-app-kit/commit/d20a1e93f2ce4572067172e6b00c8abfa21ad2f0

NPM should now default to HTTP request instead of SSH. Sorry for accidentally commiting straight to master @krivachy.

**Comment by kimmobrunfeldt** [comment] 2016-05-24 20:58
@VashMar can you confirm that `npm install` works now?

**Comment by VashMar** [comment] 2016-05-24 21:10
Yes!  Actually we got it working with resetting our ssh keys. Build succeeded, thanks!

**Comment by kimmobrunfeldt** [comment] 2016-05-24 21:19
Ok great! I'll close this issue.

**Closed by kimmobrunfeldt** 2016-05-24 21:19 UTC
